version: '3.9'

services:
  sql_backend:
    build:
      context: ./SQL_BE
      dockerfile: Dockerfile # Assuming the Dockerfile for SQL_BE is in ./SQL_BE
    container_name: sql_backend_container
    networks:
      - app_network
    ports:
      - "3306:3306" # Adjust if SQL_BE uses a different port
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Replace with your credentials
      MYSQL_DATABASE: your_database # Adjust to your database name
      MYSQL_USER: your_user # Replace with your credentials
      MYSQL_PASSWORD: your_password # Replace with your credentials
  
  springboot_app:
    build:
      context: ./SpringBootApplication
      dockerfile: Dockerfile # Assuming the Dockerfile for Spring Boot is in ./SpringBootApplication
    container_name: springboot_app_container
    networks:
      - app_network
    ports:
      - "8080:8080" # Adjust if Spring Boot uses a different port
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sql_backend:3306/your_database
      SPRING_DATASOURCE_USERNAME: your_user
      SPRING_DATASOURCE_PASSWORD: your_password

networks:
  app_network:
    driver: bridge
